### ISSUE TITLE
Bug: Crashes after a single file is attempted

### ISSUE THREAD

**Issue by CoachKidd** [KkEi34/confluence-to-obsidian-plugin#2] opened 2023-10-04 21:28 UTC
GIVEN I've installed the community plug-in for Obsidian 
WHEN I choose "Import Confluence space" from the Obsidan command palette AND I add the path to the Confluence space folder (located within the Obsidian vault)
THEN only 2 folders are extracted containing a single MD file which is still in HTML

**Comment by KkEi34** [comment] 2023-10-05 19:55
I've checked import of a confluence space located inside an obsidian vault and unfortunately was not able to reproduce the problem - the space was successfully imported. 

Plz provide some specifics:
- OS version
- pandoc version
- It would be nice, if you could send me compressed vault with the steps to reproduce.

**Comment by CoachKidd** [comment] 2023-10-06 08:32
Thanks for the reply.  I was hoping that this wasn't a zombie project.  I'm happy it appears not.

- I'm running macOS Sonoma vn 14.0
- Pandoc 3.1.8

As for files, I'm happy to share zips of the Obsidian vault and the Confluence space export.  Please contact me directly and I'll email them to you.

**Comment by KkEi34** [comment] 2023-10-08 15:36
Hi!
Thanks for trying the plugin.
Please update the plugin to the v. 0.2.5.
Let me know, if you encounter any problems.

Best of luck!

PS.
I wouldn't recommend importing from a confluence space located within the same Obsidian vault.

**Comment by KkEi34** [comment] 2023-10-13 16:51
Fixed in v. 0.2.5

**Closed as completed by KkEi34** 2023-10-13 16:51 UTC
